/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.niufeemanagment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Deepak Kumar
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }
    
    int id = 0;
    
    int getId()
    { 
       ResultSet rs = null;
     try
      {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url ="jdbc:mysql://localhost:3306/niufee?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con =  DriverManager.getConnection(url,"root","Deepaksingh@09");
        String sql = "select max(id) from signup";
        Statement st = con.createStatement();
        
        rs = st.executeQuery(sql);
        
        while(rs.next())
        {   
            id = rs.getInt(1);
            id++;
            
        }
        
      }
     catch(Exception e)
     {
        JOptionPane.showMessageDialog(null, "ERROR! Can't Connect to server");
            e.printStackTrace();
     }
     return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cntxt1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fntxt1 = new javax.swing.JTextField();
        lntxt1 = new javax.swing.JTextField();
        utxt1 = new javax.swing.JTextField();
        cptxt1 = new javax.swing.JPasswordField();
        lbtn = new javax.swing.JButton();
        subtn = new javax.swing.JButton();
        cbtn = new javax.swing.JButton();
        ptxt1 = new javax.swing.JPasswordField();
        cpcheck = new javax.swing.JLabel();
        pcheck = new javax.swing.JLabel();
        mcheck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("SIGN UP");

        // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 140));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 130, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 160, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 100, 30));

        cntxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cntxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntxt1ActionPerformed(evt);
            }
        });
        cntxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cntxt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cntxt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cntxt1KeyTyped(evt);
            }
        });
        getContentPane().add(cntxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 190, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Contact No");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 100, 30));

        fntxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fntxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(fntxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 190, 30));

        lntxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lntxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lntxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(lntxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 190, 30));

        utxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        utxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(utxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 190, 30));

        cptxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cptxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cptxt1ActionPerformed(evt);
            }
        });
        cptxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cptxt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cptxt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cptxt1KeyTyped(evt);
            }
        });
        getContentPane().add(cptxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 190, 30));

        lbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbtn.setText("Login");
        lbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtnActionPerformed(evt);
            }
        });
        getContentPane().add(lbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 110, 30));

        subtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subtn.setText("Sign Up");
        subtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtnActionPerformed(evt);
            }
        });
        getContentPane().add(subtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 100, 30));

        cbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbtn.setText("Clear");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 100, 30));

        ptxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ptxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ptxt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ptxt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptxt1KeyTyped(evt);
            }
        });
        getContentPane().add(ptxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 190, 30));

        cpcheck.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(cpcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 180, 30));

        pcheck.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(pcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 190, 30));

        mcheck.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(mcheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtnActionPerformed
       Login l1 = new Login();
       l1.show();
       this.dispose();
       
    }//GEN-LAST:event_lbtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
       fntxt1.setText("");
        lntxt1.setText("");
        utxt1.setText("");
        ptxt1.setText("");
        cptxt1.setText("");
        cntxt1.setText("");   
    }//GEN-LAST:event_cbtnActionPerformed

    private void fntxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntxt1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_fntxt1ActionPerformed

    private void lntxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lntxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lntxt1ActionPerformed

    private void utxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utxt1ActionPerformed

    private void cptxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cptxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cptxt1ActionPerformed

    private void cntxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cntxt1ActionPerformed

    private void subtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtnActionPerformed
       Validation();
       if(Validation())
       {
           insertData();
       }
       else
       {
         JOptionPane.showMessageDialog(this,"Validation Issuse."); 
       }
    }//GEN-LAST:event_subtnActionPerformed

    private void ptxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxt1KeyPressed
      passwordCheck();
      // TODO add your handling code here:
    }//GEN-LAST:event_ptxt1KeyPressed

    private void ptxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxt1KeyReleased
      passwordCheck();
      // TODO add your handling code here:
    }//GEN-LAST:event_ptxt1KeyReleased

    private void ptxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptxt1KeyTyped
      passwordCheck();
      // TODO add your handling code here:
    }//GEN-LAST:event_ptxt1KeyTyped

    private void cptxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptxt1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cptxt1KeyPressed

    private void cptxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptxt1KeyReleased
      // TODO add your handling code here:
    }//GEN-LAST:event_cptxt1KeyReleased

    private void cptxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cptxt1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cptxt1KeyTyped

    private void cntxt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxt1KeyPressed
      mobileCheck();  // TODO add your handling code here:
    }//GEN-LAST:event_cntxt1KeyPressed

    private void cntxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxt1KeyReleased
       mobileCheck(); // TODO add your handling code here:
    }//GEN-LAST:event_cntxt1KeyReleased

    private void cntxt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cntxt1KeyTyped
      mobileCheck();   // TODO add your handling code here:
    }//GEN-LAST:event_cntxt1KeyTyped
    String fname, lname, uname, password, cpassword, number;
    
    void insertData()
    {
      try
      {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url ="jdbc:mysql://localhost:3306/niufee?zeroDateTimeBehavior=CONVERT_TO_NULL";
        Connection con =  DriverManager.getConnection(url,"root","Deepaksingh@09");
        
        String sql = "insert into signup values (?,?,?,?,?,?)";
      PreparedStatement st = con.prepareStatement(sql);
      
      st.setInt(1, getId());
      st.setString(2, fname);
      st.setString(3,lname);
      st.setString(4,uname);
      st.setString(5,password);
      st.setString(6,number);
      int i = st.executeUpdate();
      
      if(i>0)
      {
          JOptionPane.showMessageDialog(this,"Record Inserted Succesfully");
      }
      else
      {
        JOptionPane.showMessageDialog(this,"Record  Not Inserted Succesfully");
      }
                
      }
      catch(Exception e)
      {
        JOptionPane.showMessageDialog(null, "ERROR! Can't Connect to server");
         e.printStackTrace(); 
      }
    }
    
    
    
    boolean Validation()
    {
        fname = fntxt1.getText();
        lname = lntxt1.getText();
        uname = utxt1.getText();
        password = ptxt1.getText();
        cpassword = cptxt1.getText();
        number = cntxt1.getText(); 
        if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter First Name...");
            return false;
        }
        if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Last Name...");
            return false;
        }
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter UserName...");
            return false;
        }
        if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Your Password...");
            return false;
        }
        if(cpassword.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Confirm Your Password...");
            return false;
        }
         if(number.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Enter Your Number...");
            return false;
        }
        return true;    
    }
    
    void passwordCheck()
    {
       password = ptxt1.getText();
       if(password.length()>=8)
       {
           pcheck.setText(""); 
       }
       else
       {
           pcheck.setText("Enter 8 Digit Password");
       }
       
    }
    
   void mobileCheck()
   {
      number = cntxt1.getText(); 
      if(number.length()==10)
      {
          mcheck.setText("");
      }
      else
      {
        mcheck.setText("Enter 10 Digit Contact Number.");  
      }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cbtn;
    private javax.swing.JTextField cntxt1;
    private javax.swing.JLabel cpcheck;
    private javax.swing.JPasswordField cptxt1;
    private javax.swing.JTextField fntxt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lbtn;
    private javax.swing.JTextField lntxt1;
    private javax.swing.JLabel mcheck;
    private javax.swing.JLabel pcheck;
    private javax.swing.JPasswordField ptxt1;
    private javax.swing.JButton subtn;
    private javax.swing.JTextField utxt1;
    // End of variables declaration//GEN-END:variables
}
